#!/home/benpeng/nbifweb_client/software/node/bin/node
var mysql           = require('mysql');
let querystring     = require('querystring');
let http            = require('http');
var moment          = require('moment');
let process         = require('process');
let cronJob         = require("cron").CronJob;
let child_process   = require('child_process');
let fs              = require('fs');
let rtlogintime     = {
  s : '00',
  m : '00',
};
let maxPS           = 20;
let maxPSperson     = 2;
let overallusage    = {};
let djregxfail      = /dj exited with errors/;
let djregxpass      = /dj exited successfully/;
let syncregxpass    = /All syncs OK/;
let R               = child_process.execSync('whoami',{
  encoding  : 'utf8'
}).split('\n');
let whoami=R[0];
console.log('whoami : '+R[0]);
let HOME            = '/proj/cip_nbif_de_1/sanitycheck';
let variants        = ['nbif_nv10_gpu','nbif_draco_gpu','nbif_et_0','nbif_et_1','nbif_et_2'];//TODO pick up from DB in the future
/////////////////////////
//rt_login
/////////////////////////
let cron_rtlogin = new cronJob(rtlogintime.s+' '+rtlogintime.m+' * * * *',function(){
  cron_check.stop();
  child_process.exec('~/nbifweb_client/software/tools/rtlogin',function(err,stdout,stderr){
    if(err) {
      throw err;
    }
    let regx  = /you must use a password/;
    if(regx.test(stdout)){
      console.log(stdout);
      cron_check.start();
    }
    else{
      child_process.execSync('rm -rf /home/benpeng/.jfrog/');
      child_process.exec('~/nbifweb_client/software/tools/rtlogin',function(err1,stdout1,stderr1){
        if(err1) {
          child_process.execSync('mutt Benny.Peng@amd.com -s [NBIF][Sanity][RTLOGINFAIL]');
          throw err1;
        }
        if(regx.test(stdout)){
          cron_check.start();
        }
        else{
          child_process.execSync('mutt Benny.Peng@amd.com -s [NBIF][Sanity][RTLOGINFAIL]');
          throw 'need fix';
        }
      });
    }
  });
},null,true,'Asia/Chongqing');
/////////////////////////
//=======================
/////////////////////////

/////////////////////////
//Check shelve
/////////////////////////
let cron_check = new cronJob('*/5 * * * * *',function(){
  let details       = {};
  let treeRoot      = '';
  let username      = '';
  let shelve        = '';
  let codeline      = '';
  let branch_name   = '';
  let resultlocation= '';
  let numberofresult;
  let connection = mysql.createConnection({
    host     : 'atlvmysqldp19.amd.com',
    user     : 'nbif_ad',
    password : 'WqyaSp90*',
    database : 'nbif_management_db'
  });
  connection.connect(function(err){
    if(err) {
      console.log(err);
      return;
    }
    //DB connection succeed
    let sql = '';
    sql +=  'select * from sanityshelves  where result="NOTSTARTED"';
    connection.query(sql,function(err1,stdout1,stderr1){
      if(err1){
        console.log(err1);
        return;
      }
      //pick up one result
      if(stdout1.length == 0){
        console.log('no new shelve submitted');
      }
      else{
        console.log('new shelve(s) found');
        let pickedupshelve  = stdout1[0];
        numberofresult  = JSON.parse(pickedupshelve.testlist).length  * variants.length + variants.length * 1;//1 for dcelabe
        treeRoot  = HOME+'/'+
      }
    });
    /////////////////////////
    //Start main task
    /////////////////////////
  });
  
},null,false,'Asia/Chongqing');
/////////////////////////
//=======================
/////////////////////////
