#!/tool/pandora64/bin/tcsh
set   treeRoot  = `pwd`;
set   username  = `whoami`;
set   hostname  = `hostname`;
set   configuration_id  = `cat $treeRoot/configuration_id`;
set   passwd    = \!:1;
echo $treeRoot;
echo $username;
echo $hostname;
echo $configuration_id;
sshpass -p $passwd ssh -o StrictHostKeyChecking=no $username@srdcws808 "/local_vol1_nobackup/nbiftools/nbif_chk_sanity.js -cid $configuration_id -u $username -h $hostname -r $treeRoot"
