#!/home/benpeng/nbifweb_client/software/node/bin/node
let process = require('process');
let fs = require('fs');
console.log(process.argv);
let str = '{';
for (let i=3;i<process.argv.length;i++){
  str += process.argv[i];
  str += ',';
}
str += '}';

let lines = fs.readFileSync('./NBIF_TREE_INFO','utf8').split('\n');
lines.pop();
let regx01  = /(\w+):::(\S+)/;
let projectname;
let shelve;
let kickoffdate;
let variantname;
let isBAPU;
let codeline;
let branch_name;
let changelist;
for(let l=0;l<lines.length;l++){
  lines[l].replace(regx01,function(rs,$1,$2){
    console.log($1,$2);
    if($1 == 'projectname'){
      projectname = $2;
    }
    if($1 == 'shelve'){
      shelve  = $2;
    }
    if($1 == 'kickoffdate'){
      kickoffdate = $2;
    }
    if($1 == 'variantname'){
      variantname = $2;
    }
    if($1 == 'isBAPU'){
      isBAPU  = $2;
    }
  });
}
lines = fs.readFileSync('./configuration_id','utf8').split('\n');
regx01  =/(\w+)\/(\w+)@(\w+)/;
lines.pop();
lines[0].replace(regx01,function(rs,$1,$2,$3){
  codeline  = $1;
  branch_name = $2;
  changelist  = $3;
});
let onecase = {
  codeline  : codeline,
  projectname : projectname,
  variantname : variantname,
  branch_name : branch_name,
  kickoffdate : kickoffdate,
  isBAPU      : isBAPU,
  shelve      : shelve,
  testname    : process.argv[2],
  outdir      : process.argv[3]
};
console.log(onecase);
fs.writeFileSync('endlog',JSON.stringify(onecase),{
  encoding  : 'utf8',
  mode      : '0600',
  flag      : 'w'
  
});
//let querystring     = require('querystring');
//let http            = require('http');
//let fs              = require('fs');
//let child_process   = require('child_process');
//let cronJob         = require("cron").CronJob;
//const postData = querystring.stringify({
//  'msg': 'Hello World!'
//});
//
//const options = {
//  hostname: 'www.google.com',
//  port: 80,
//  path: '/upload',
//  method: 'POST',
//  headers: {
//    'Content-Type': 'application/x-www-form-urlencoded',
//    'Content-Length': Buffer.byteLength(postData)
//  }
//};
//
//const req = http.request(options, (res) => {
//  console.log(`STATUS: ${res.statusCode}`);
//  console.log(`HEADERS: ${JSON.stringify(res.headers)}`);
//  res.setEncoding('utf8');
//  res.on('data', (chunk) => {
//    console.log(`BODY: ${chunk}`);
//  });
//  res.on('end', () => {
//    console.log('No more data in response.');
//  });
//});
//
//req.on('error', (e) => {
//  console.error(`problem with request: ${e.message}`);
//});
//
//// Write data to request body
//req.write(postData);
//req.end();
