#!/home/benpeng/nbifweb_client/software/node/bin/node
let process = require('process');
console.log(process.argv);
let querystring     = require('querystring');
let http            = require('http');
//let fs              = require('fs');
//let child_process   = require('child_process');
//let cronJob         = require("cron").CronJob;
const postData = querystring.stringify({
  'treeRoot': '/proj/cip_floyd_genz/ip_regression/nbif.regression.branch.mi200.nbif_nv10_gpu.group1.1'
});

const options = {
  hostname: 'localhost',
  port: 9001,
  path: '/try/start',
  method: 'POST',
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded',
    'Content-Length': Buffer.byteLength(postData)
  }
};

const req = http.request(options, (res) => {
  console.log(`STATUS: ${res.statusCode}`);
  console.log(`HEADERS: ${JSON.stringify(res.headers)}`);
  res.setEncoding('utf8');
  res.on('data', (chunk) => {
    console.log(`BODY: ${chunk}`);
  });
  res.on('end', () => {
    console.log('No more data in response.');
  });
});

req.on('error', (e) => {
  console.error(`problem with request: ${e.message}`);
});

// Write data to request body
req.write(postData);
req.end();
