#!/home/benpeng/nbifweb_client/software/node/bin/node
let querystring     = require('querystring');
let http            = require('http');
let process         = require('process');
let child_process   = require('child_process');
let fs              = require('fs');

console.log('DBG');
console.log(process.argv[2]);
console.log(process.argv[3]);

//const postData = querystring.stringify({
//  'msg': 'Hello World!'
//});
//
//const options = {
//  hostname: 'www.google.com',
//  port: 80,
//  path: '/upload',
//  method: 'POST',
//  headers: {
//    'Content-Type': 'application/x-www-form-urlencoded',
//    'Content-Length': Buffer.byteLength(postData)
//  }
//};
//
//const req = http.request(options, (res) => {
//  console.log(`STATUS: ${res.statusCode}`);
//  console.log(`HEADERS: ${JSON.stringify(res.headers)}`);
//  res.setEncoding('utf8');
//  res.on('data', (chunk) => {
//    console.log(`BODY: ${chunk}`);
//  });
//  res.on('end', () => {
//    console.log('No more data in response.');
//  });
//});
//
//req.on('error', (e) => {
//  console.error(`problem with request: ${e.message}`);
//});
//
//// Write data to request body
//req.write(postData);
//req.end();
